// <auto-generated />
namespace MvcAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class viewAdminData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(viewAdminData));
        
        string IMigrationMetadata.Id
        {
            get { return "201811060733343_viewAdminData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
